#!/usr/bin/env python3
"""Generate .env.local for NextChat — show only local llama-server models."""
import json
import os
import sys
import urllib.request
from pathlib import Path

NEXTCHAT_DIR = Path(__file__).resolve().parent.parent.parent / "hermes" / "data" / "nextchat"
LLAMA_URL = "http://127.0.0.1:8080"


def get_llama_models():
    """Query llama-server for available models."""
    try:
        with urllib.request.urlopen(f"{LLAMA_URL}/v1/models", timeout=5) as r:
            data = json.loads(r.read())
            models = [m["id"] for m in data.get("data", [])]
            return models if models else ["local-model"]
    except Exception:
        return ["local-model"]


def all_cloud_models():
    """Major cloud models to hide (too many to list all, hit top ones)."""
    return [
        # OpenAI
        "gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-4-1106-preview",
        "gpt-4-vision-preview", "gpt-4-0125-preview", "gpt-4-32k",
        "gpt-3.5-turbo", "gpt-3.5-turbo-1106", "gpt-3.5-turbo-16k",
        "gpt-3.5-turbo-instruct",
        "o1", "o1-mini", "o1-preview", "o3-mini",
        # Claude
        "claude-3-5-sonnet-20241022", "claude-3-5-sonnet-20240620",
        "claude-3-opus-20240229", "claude-3-sonnet-20240229",
        "claude-3-haiku-20240307",
        # Gemini
        "gemini-pro", "gemini-1.5-pro", "gemini-1.5-flash",
        "gemini-2.0-flash-exp",
        # DeepSeek
        "deepseek-chat", "deepseek-v3", "deepseek-r1",
        # Other
        "glm-4", "qwen-max", "moonshot-v1-8k", "moonshot-v1-32k",
    ]


def generate_env(models):
    """Write .env.local for NextChat."""
    # Build CUSTOM_MODELS: hide cloud models, show local models
    parts = []
    for m in all_cloud_models():
        parts.append(f"-{m}")
    for m in models:
        # Clean model name for display
        display = m.replace("_", ".").replace("-instruct", "").replace("-chat", "")
        parts.append(f"+{m}={display} (Local)")

    custom_models = ",".join(parts)

    env_content = f"""# Auto-generated by Hermes — {__file__}
# Do not edit manually. Regenerated on each launch.

# Point to local llama-server
BASE_URL=http://127.0.0.1:8080
OPENAI_API_KEY=sk-no-key-needed

# Hide API key input from users
HIDE_USER_API_KEY=1

# Show only local models, hide cloud models
CUSTOM_MODELS={custom_models}

# Disable analytics
GTM_ID=
"""

    env_path = NEXTCHAT_DIR / ".env.local"
    env_path.write_text(env_content, encoding="utf-8")
    print(f"[nextchat-config] wrote {env_path} with {len(models)} local model(s)")


def main():
    if not NEXTCHAT_DIR.exists():
        print("[nextchat-config] NextChat dir not found, skipping")
        return 0

    models = get_llama_models()
    generate_env(models)
    return 0


if __name__ == "__main__":
    sys.exit(main())
